### ISSUE TITLE
Can't Build it with Intel XDK ('CamScannerOpenAPIFramework/CamScannerOpenAPIController.h' file not found)

### ISSUE THREAD

**Issue by saormart** [Beelphegor/cordova-camscanner#3]
I'm facing the follow error when try to build it with Intel XDK platform:

> --serialize-diagnostics .../cordova_project/platforms/ios/build/CamScanner.build/Release-iphoneos/CamScanner.build/Objects-normal/armv7/CordovaCamscanner.dia -c .../cordova_project/platforms/ios/CamScanner/Plugins/cordova-camscanner/CordovaCamscanner.m -o .../cordova_project/platforms/ios/build/CamScanner.build/Release-iphoneos/CamScanner.build/Objects-normal/armv7/CordovaCamscanner.o
> .../cordova_project/platforms/ios/CamScanner/Plugins/cordova-camscanner/CordovaCamscanner.m:3:9: fatal error: 'CamScannerOpenAPIFramework/CamScannerOpenAPIController.h' file not found

**Comment by saormart** [comment]
Hi there, I have fixed the issue by delete the file named: "Current" and rename the folder "A" to "Current" on the follow directory: "cordova-camscanner/lib/ios/CamScannerOpenAPIFramework.framework/Versions/"

**Comment by sandrobirke** [comment]
now i have a new Error:

> CompileC /Users/admin/Library/Developer/Xcode/DerivedData/RegisafeCapture-fesmtragugebfnaycctiydouagpb/Build/Intermediates/RegisafeCapture.build/Debug-iphonesimulator/RegisafeCapture.build/Objects-normal/x86_64/CordovaCamscanner.o RegisafeCapture/Plugins/cordova-camscanner/CordovaCamscanner.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
