### ISSUE TITLE
It's not a issue, it's more a question...

### ISSUE THREAD

**Issue by saormart** [Beelphegor/cordova-camscanner#6]
Hi there, I would like to know if it's possible to process the image without open the camscanner app.
I'm asking that, because on camscanner dev website they says that for:
**Authorized App(Free)**
-Limited number of times to use OpenAPI 
-Returned file type limited to jpeg 
-Limited enhancement modes 
-Results saved in CamScanner 
**-Icon of CamScanner displayed in image cropping and enhancing process**

So, just the "Icon" is displayed for the free version!

Thanks!

**Comment by Beelphegor** [comment]
Sorry for late response, but I understand you do need to have camscanner installed, any version of camscanner works, even the free version.
